# leader
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# basic setting
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_status_background "default"
set -g @catppuccin_window_status_style "rounded"

set -g mouse on

set -g history-limit 10000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -s escape-time 0

# keybinds
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# status bar
set -g status-justify absolute-centre

set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_current_fill "all"

set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}%H:%M %d-%b-%y"

set -g allow-rename off
set -g automatic-rename on
set -g automatic-rename-format '#{?#{==:#{pane_current_command},nvim},#{pane_title},#{b:pane_current_path}}'

set -g window-status-format '#I'
set -g window-status-current-format '#I'
