# leader
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# basic setting
set -g default-terminal "screen-256color"

set -g mouse on

set -g history-limit 10000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -s escape-time 0

# keybinds
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# status bar
set -g status-style bg=black,fg=white
set -g status-left-length 20
set -g status-left "#[fg=green]#S "
set -g status-right "#[fg=cyan]%Y-%m-%d %H:%M"
setw -g window-status-current-style fg=black,bg=green,bold
